### ISSUE TITLE
SoftAP still running even after captive portal results in WL_CONNECTED.

### ISSUE THREAD

**Issue by Alives** [Hieromon/AutoConnect#107]
The only way to get rid of the SoftAP is to reset the board and let it try WiFi.begin() successfully on boot.  SoftAP doesn't seem to stop after a captive portal session.

```
  config.apid = sensor_name.c_str();
  config.psk = F("");
  config.autoReconnect = true;
  config.portalTimeout = 60000;  // Timeout in 60s.
  portal.config(config);
  portal.begin();
```

**Comment by Hieromon** [comment]
It is not the issue and is an intentional behavior as the specification.
