### ISSUE TITLE
autoreconnect doesn't seem to be working

### ISSUE THREAD

**Issue by Alives** [Hieromon/AutoConnect#108]
After my captive portal times out, I'd expect a loop of WiFi.begin() -> Captive Portal again, then once an SSID is set, WiFi.begin().  I'm seeing the captive portal timeout, then nothing happens.

```
  config.apid = sensor_name.c_str();
  config.psk = F("");
  config.autoReconnect = true;
  config.portalTimeout = 60000;  // Timeout in 60s.
  portal.config(config);
  portal.begin();
```

**Comment by Hieromon** [comment]
Once successfully connected to the SSID, AutoConnect loads and reconnects with its credential, even if disconnected once.
I can not reproduce the situation. autoReconnect works fine.

Please provide me a serial log based on the information written in the [documentation](https://hieromon.github.io/AutoConnect/faq.html#4-reports-the-issue-to-autoconnect-github-repository) to problem diagnostic.

**Comment by Hieromon** [comment]
It closes because there is no answer. Please reopen if an answer occurs.
