### ISSUE TITLE
AutoConnectConfig API parameters

### ISSUE THREAD

**Issue by OoM-JaN** [Hieromon/AutoConnect#115]
Reading thru the manual I found a minor spelling error:
AutoConenct has to be AutoConnect.
![image](https://user-images.githubusercontent.com/53234680/61951174-7eebd380-afb0-11e9-885c-7a1dd3845fd4.png)

Probably not the place but didn't know where else ;-)

Real issue is that I cant manage to set the right parameter when there is no internet connection. I managed to change the ssid when in AP mode but nothing else.
I use the implementation describd here: https://hieromon.github.io/AutoConnect/howtoembed.html): 

In global the next works:
```
AutoConnectConfig 
Config("myssid","");
```
I want to change the IP when in AP mode with the following code:
```
Config.staip = IPAddress(192,168,4,1);
portal.config(Config);
```
Putting this code in global fails and when put in void setup () it changes the IP in both modes AP and Station mode. 

What am I missing here? I think I need to know in which mode the ESP8266 is but other then on my serial output I don't see how?

**Comment by Hieromon** [comment]
@OoM-JaN, 
> AutoConenct has to be AutoConnect.

Thank you notify. It had been fixed.

**Comment by Hieromon** [comment]
Use the [AutoConnectConfig::apip](https://hieromon.github.io/AutoConnect/apiconfig.html#apip) to change the IP address of the ESP module that is in Soft AP state when launching the captive portal.

**Comment by OoM-JaN** [comment]
My stupid mistake! With apip it worked instantly. Thanks!
