### ISSUE TITLE
AsyncWebServer

### ISSUE THREAD

**Issue by AlexFundorin** [Hieromon/AutoConnect#117]
Seems promising, but why don't you use AsyncWebServer instead of a regular one?

**Comment by Hieromon** [comment]
I know that it is useful for someone. But, the current AutoConnect enhancements are not over.
Developing a similar of AutoConnect based on ESPAsyncWebServer is not just porting. I have to continue with the code analysis of AsyncWebServer and need to remake the PageBuilder. Unfortunately, I do not have enough time to develop a similar AutoConnect featuring ESPAyncWebServer.
Of course, you can do it.
