### ISSUE TITLE
Can anyone help me make this code compatible with AutoConnect?

### ISSUE THREAD

**Issue by marrobHD** [Hieromon/AutoConnect#13]
Thats my Code:

Hastebin link: https://hastebin.com/elagoqayim.cpp

Thanks for help!

~Marlon

**Comment by Hieromon** [comment]
I don't have time to look into your code in detail. Looking at the code overview, it seems that AutoConnect can be embedded in setup_wifi(). However, I did not investigate all of your code. A detailed explanation of how to embed AutoConnect is documented. Please refer to https://hieromon.github.io/AutoConnect

1. Insert ```#include <AutoConnect.h>``` to the bottom of include headers.
2. Define ```AutoConnect Portal;``` before ```void setup()``` function.
3. Comment out the below step.
```
L266: WiFi.mode(WIFI_STA);
L267: WiFi.begin(ssid, password);
```
4. Insert a new line as ```Portal.begin()``` at behind of the commented out line.
5. Insert ```Portal.handleClient();``` behind of ```showleds();``` in ```void loop()``` function.

**Comment by Hieromon** [comment]
Since there was no response even after one month passed, closed this issue.
When some reports are posted, reopen it.
