### ISSUE TITLE
Can't compile even the supplied examples ex Simple

### ISSUE THREAD

**Issue by mikekgr** [Hieromon/AutoConnect#130]
Dear Sirs,
I can't compile even the supplied examples, in this case the "Simple" sketch
My system has:
OS: Windows 10
Arduino: 1.8.8 & 1.8.10 
AutoConnect library: 1.0.2
ESP8266 Arduino Core: latest master from Git
Tested sketch: Simple.ino 

Errors in Arduino compalition:

E:\ARDUINO_ESP_DEV\arduino-IDE\portable\sketchbook\libraries\AutoConnect\src\AutoConnectUpdate.cpp: In member function 'String AutoConnectUpdateAct::_onCatalog(AutoConnectAux&, PageArgument&)':

E:\ARDUINO_ESP_DEV\arduino-IDE\portable\sketchbook\libraries\AutoConnect\src\AutoConnectUpdate.cpp:399:20: error: 'class ArduinoJson::StaticJsonBuffer<256u>' has no member named 'success'

         parse = jb.success();

                    ^

E:\ARDUINO_ESP_DEV\arduino-IDE\portable\sketchbook\libraries\AutoConnect\src\AutoConnectUpdate.cpp:420:71: error: 'err' was not declared in this scope

           caption.value = String(F("Invalid catalog list:")) + String(err.c_str());

Please help me to solve the problem and to enjoy this very good library.

Thanks and Best Regards,
Mike Kranidis

**Comment by Hieromon** [comment]
Sorry, the Travis build script was incorrect and could not detect the issue which combines with ArduinoJson 5.
I re-release v1.0.2 including the patch to fix.
