### ISSUE TITLE
Sometimes an instant disconnect occurs after resetting the controller

### ISSUE THREAD

**Issue by Boldie** [Hieromon/AutoConnect#139]
Sometimes after soft resetting the controller the AutoConnect does not work as expected. This happens due to an uninitalized member _rfDisconnect in class AutoConnect. This is a bool and bools shall be initialized every time before usage.

**Comment by Hieromon** [comment]
@Boldie You found an important potential bug and I overlooked it at all.
Thank you for your contribution.
