### ISSUE TITLE
Debug Messages

### ISSUE THREAD

**Issue by fabltd** [Hieromon/AutoConnect#148]
Hello 

Is there a way to deal with the following:

E][WebServer.cpp:617] _handleRequest(): request handler not found
[E][WebServer.cpp:617] _handleRequest(): request handler not found
[E][WebServer.cpp:617] _handleRequest(): request handler not found
[E][WiFiClient.cpp:392] write(): fail on fd 62, errno: 104, "Connection reset by peer"
[E][WebServer.cpp:617] _handleRequest(): request handler not found

What request handler is not found??

**Comment by Hieromon** [comment]
Close due to no report for one month. Please reopen if an answer occurs.
