### ISSUE TITLE
wiki sample error - Custom Web pages with AutoConnect

### ISSUE THREAD

**Issue by HackThatNow** [Hieromon/AutoConnect#151]
sample code 
'AutoConnectAux  aux1("/mqtt_setting", "MQTT Setting", { header, caption1, save });'

should be

'AutoConnectAux aux1("/mqtt_setting", "MQTT Setting", true, {header, caption1, save});' 

https://hieromon.github.io/AutoConnect/acintro.html

**Comment by Hieromon** [comment]
Thank you report.
The wrong code has corrected.
