### ISSUE TITLE
variable 'sdVerify' set but not used (AutoConnectUploadSD::_open)

### ISSUE THREAD

**Issue by adynis** [Hieromon/AutoConnect#156]
Minor observation:
When AC_DEBUG is NOT set, when I compile the code with PlatformIO I get the following warning:

> In file included from 
> C:\users\....\.platformio\lib\AutoConnect_ID2678\src\AutoConnectAux.cpp:13:0:
> C:\users\....\.platformio\lib\AutoConnect_ID2678\src\AutoConnectUploadImpl.h: In member function 'virtual bool AutoConnectUploadSD::_open(const char*, const char*)':
> C:\users\....\.platformio\lib\AutoConnect_ID2678\src\AutoConnectUploadImpl.h:149:17: warning: variable 'sdVerify' set but not used [-Wunused-but-set-variable]
>      const char* sdVerify;
>____________^

It's not a real problem, but it would be nice to get rid of this warning in future versions.
Thanks,

PS. In PlatformIO it can be ignored by adding in platformio.ini, under: [env:\<platform\>] 
build_flags =  -Wno-unused-but-set-variable

**Comment by Hieromon** [comment]
You are right. I have already committed a [fix](https://github.com/Hieromon/AutoConnect/commit/07b4af87ae4900f219bee3cdb99ab3290237317d) to the [patches/v113](https://github.com/Hieromon/AutoConnect/tree/patches/v113) branch.
I will release the v113 with some minor fixes.
Thank you for the reports.
