### ISSUE TITLE
Web interface for PC browser

### ISSUE THREAD

**Issue by RaphaelGirardRioTinto** [Hieromon/AutoConnect#162]
Hi.

I am interresting in using your Config.ino sketch for one of my project. It is working pretty well and it is doing exactly what I need, configuring IP adress when in "config mode" over a web interface.

Right now, I don't have access to the web interface with a PC browser, such as Google Chrome or Internet Explorer. When using a smartphone, the interface is poping just as it should. When using a PC web browser, I don't have any popup at all. 

Is it possible to activate the interface popup for a PC browser ?
Is it possible to reach the web interface with a url, such as 172.217.28.1/Config?

Thank you.
Raphaël

**Comment by Hieromon** [comment]
I tested Chrome on Windows 10. It works fine.
