### ISSUE TITLE
Multiple library error

### ISSUE THREAD

**Issue by isquarebsys** [Hieromon/AutoConnect#164]
Dear Hiero
I have Arduino 1.8 and ESP8266 library 2.6.3. I am getting error as below. Could you please help
Similar error happens for ESP32 as well

Arduino: 1.8.10 (Windows 8.1), Board: "WeMos D1 R1, 80 MHz, Flash, Disabled (new can abort), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), v2 Lower Memory, Disabled, None, Only Sketch, 921600"

Multiple libraries were found for "PageBuilder.h"
 Used: D:\ws\git\iot\board-wise\arduino\libraries\PageBuilder
Multiple libraries were found for "ESP8266WiFi.h"
In file included from D:\ws\git\iot\board-wise\arduino\libraries\AutoConnect\src/AutoConnectAux.h:22:0,

 Used: C:\Users\user\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\libraries\ESP8266WiFi
Multiple libraries were found for "ESP8266WebServer.h"
 Used: C:\Users\user\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\libraries\ESP8266WebServer
                 from D:\ws\git\iot\board-wise\arduino\libraries\AutoConnect\src/AutoConnect.h:34,

Multiple libraries were found for "AutoConnect.h"
 Used: D:\ws\git\iot\board-wise\arduino\libraries\AutoConnect
                 from C:\Users\user\Documents\Arduino\sketch_dec19a\sketch_dec19a.ino:3:

Multiple libraries were found for "DNSServer.h"
D:\ws\git\iot\board-wise\arduino\libraries\AutoConnect\src/AutoConnectElement.h:15:25: fatal error: ArduinoJson.h: No such file or directory

 Used: C:\Users\user\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\libraries\DNSServer
 #include <ArduinoJson.h>

Multiple libraries were found for "EEPROM.h"
                         ^

 Used: C:\Users\user\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.0\libraries\EEPROM
compilation terminated.

exit status 1
Error compiling for board WeMos D1 R1.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by Hieromon** [comment]
The library is not properly installed. The compiler recognized for the arduino core ESP8266 2.5.0. It is not an AutoConnect issue.
Please discuss such issues in the Arduino forum.
