### ISSUE TITLE
Next button is hardcoded to use "/_ac

### ISSUE THREAD

**Issue by mukha521** [Hieromon/AutoConnect#168]
If you have changed AUTOCONNECT_URI in AutoConnectDefs.h to something custom, the "Next" button at "Configure new AP" page will be broken as it is hardcoded to use "/_ac" uri.

**Comment by Hieromon** [comment]
It has already fixed with [patches/v113](https://github.com/Hieromon/AutoConnect/tree/patches/v113).

https://github.com/Hieromon/AutoConnect/blob/07b4af87ae4900f219bee3cdb99ab3290237317d/src/AutoConnectPage.cpp#L1176
