### ISSUE TITLE
misspelling in AutoConnectConfig example

### ISSUE THREAD

**Issue by N30Pr1nc3** [Hieromon/AutoConnect#174]
Hi 

Today i used this example [https://hieromon.github.io/AutoConnect/apiconfig.html#autoconnectconfig-example](https://hieromon.github.io/AutoConnect/apiconfig.html#autoconnectconfig-example)
it took a while until i found a misspelling at:

```
Config.boundaryOffet = 64;                    // Reserve 64 bytes for the user data in EEPROM.
Config.boundaryOffset = 64;                    // Reserve 64 bytes for the user data in EEPROM.
```

**Comment by Hieromon** [comment]
Fixed. Thank you for your contribution @N30Pr1nc3.

**Comment by N30Pr1nc3** [comment]
Thanks to you this software is awsome
