### ISSUE TITLE
ESPAsyncwebserver - Question

### ISSUE THREAD

**Issue by nelsontechnologies** [Hieromon/AutoConnect#191]
Is there any advantage to using espasyncwebserver instead?  If so, how would you implement it?

Thanks!

**Comment by Hieromon** [comment]
Not blocking the ESP module process acting as a server to respond to HTTP requests addresses concurrent processing needs. It brings benefits but requires developer skills.
You can see it in the posted issue fo the ESPAsyncWebServer repository. Many people do not understand what "asynchronous" means.
I have developed AyncAutoConnect not implemented AutoConnectAux, but no plan to publish the repository, yet.

**Comment by v-c** [comment]
Any chance you will reconsider and publish AsyncAutoConnect?

**Comment by Hieromon** [comment]
@v-c I hope to publish someday but it's still incomplete. In particular, there are few problems with the method of migrating WiFi connection waiting- process from while loop to event-driven.
