### ISSUE TITLE
ondemand AP

### ISSUE THREAD

**Issue by m-menon** [Hieromon/AutoConnect#20]
Thanks for the useful library. Is there any example for an On Demand AP? Say I use a button press to put this into WiFi configuration mode ( even if it is connected to an existing WiFi station ). If I press the button for 5 seconds then I want the WiFi credentials to be wiped off and the ESP32 should restart in AP mode. The button press / delay and all I have written but need a robust way of getting the ESP32 into the AP mode. I think I did try setting the autoConnection to false but it would not get back into the AP mode unless I erase the eeprom.

The best would be that the button press gets the ESP32 into AP mode ( even if there is any saved wifi credentials ) ... then times out after a while if no new AP is set. This way one can also switch from one AP to another AP.

**Comment by Hieromon** [comment]
It is the same as WiFiManager equipped with [startConfigPortal](https://github.com/tzapu/WiFiManager/tree/development#on-demand-configuration-portal) function, right? It will be released with v0.9.7.
An **immediateStart** is added to AutoConnectConfig as a new parameter. You enable it and call **AutoConnect::begin**, the AP mode will start up immediately.

**Comment by m-menon** [comment]
> It is the same as WiFiManager equipped with startConfigPortal function, right?

Yup, that is right. Great that it is being added in the upcoming version. For now I am using the `AutoConnectCredential` to delete the saved credentials. Thanks
