### ISSUE TITLE
Examples doesn't work anymore on 1.1.5/1.1.6

### ISSUE THREAD

**Issue by schmurtzm** [Hieromon/AutoConnect#206]
Hi,

Thanks for this great library !
 
I've got problems since version 1.1.5 and 1.1.6 (working fine on 1.1.4) :
hardware : Wemos D1 mini

- With the example "mqttRSSI_NA", the captive portal displays "404 not found" in the example.

- So with a workaround, I can arrive on the configuration page with this url http://172.217.28.1/_ac/config
But when I configure my new AP nothing happens when I click on "Apply" button.

Same behavior with the "simple" example :   with this sketch I've got the captive AP working normally but "apply" button wont work.

Any idea ?

**Comment by Hieromon** [comment]
@schmurtzm Hello, Thank you for using AutoConnect.
I had reproduced the issue. AutoConnect has been degraded and is in a critical situation.
I have to fix immediately.
Thank you for your reports.
