### ISSUE TITLE
Shows older version

### ISSUE THREAD

**Issue by m-menon** [Hieromon/AutoConnect#21]
Even if one installs the latest version 0.9.6, it shows as 0.9.5. I guess the library.json still has the older ver no.

**Comment by Hieromon** [comment]
I forgot to update the version description of library.json with the initial release of v0.9.6. I fixed it, but it does not seem to be reflected in Arduino library manager.
I will release v0.9.7 soon. That will be synchronized.

**Comment by m-menon** [comment]
Cool. Thanks
