### ISSUE TITLE
Result of connection drops ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by cyp-git** [Hieromon/AutoConnect#216]
Hi!

Thanks for the great library!
I think the value for AUTOCONNECT_RESPONSE_WAITTIME in AutoConnectDefs.h should be in ms, not in s. Sorry if I'm wrong. I modified the value to 5000 and it seems to work, else the result of connection always drops ERR_CONNECTION_RESET.

**Comment by Hieromon** [comment]
@cyp-git You are right.
I will include the fix in v120. Thank you for the report.

**Comment by Hieromon** [comment]
Merged #280
