### ISSUE TITLE
invalid types 'AutoConnectAux*[const char [5]]' for array subscript

### ISSUE THREAD

**Issue by soemarko** [Hieromon/AutoConnect#239]
From the [Tips for data conversion](https://hieromon.github.io/AutoConnect/datatips.html), I can do `int value = aux["INPUT"].value.toInt();` as shorthand.

But when I tried:

```
		AutoConnectAux* auxPage = portal.aux("/app-config");
		auxPage->loadElement(file, { "key", "server", "port" });
		Serial.println(auxPage["port"].value.toInt());
```

The above error appears. No error when I tried the long way. 1 extra line is not a big deal. I'm using the esp32 dev board if that matters.

**Comment by Hieromon** [comment]
This indicated matter contains a little misleading. Due to the interpretation of C++ syntax.
An `auxPage` is a pointer, so syntactically valid ways of calling its operator[] would be:

```cpp
Serial.println((*auxPage)["port"].value.toInt());
```

or

```
Serial.println(auxPage->operator[]("port").value.toInt());
```

**Comment by Hieromon** [comment]
Closed, not AutoConnect library issue.
