### ISSUE TITLE
Not understanding - what it needs to do for me.

### ISSUE THREAD

**Issue by rowifi** [Hieromon/AutoConnect#246]
I have just moved my module using Autoconnect away from my wifi router - to emulate a loss of wifi. I left it until the Captive portal began. However, when I returned back home, it would not reconnect as it had lost the wifi credentials.
It appears that with no valid wifi, it waits for a short time and then start captive portal. Once it starts captive portal it will not reconnect without re-entering credentials.  
How can I get it never to enter captive portal without user intervention ( erasing all credentials perhaps).
If this is deployed in a building- it is possible for the power to fail losing both wifi and esp32. If the wifi takes a longer time to return, then the ESP must wait ( perhaps for hours ) until it is restored otherwise there is no way for it to recover unattended.
Is this possible?

**Comment by Hieromon** [comment]
Closed due to lack of clear specifications.
