### ISSUE TITLE
wdt error on autoconnect-enhance-autoConnectAux

### ISSUE THREAD

**Issue by ageurtse** [Hieromon/AutoConnect#25]
When using Autoconnect-enhance-autoConnectAux, i get an wdt error when using:
  
`config.apid = "arnoldg";
  config.hostName = "arnoldg";
  Portal.config(config);
  Portal.begin();
`

when programming 
`config.apid = String(AUTOCONNECT_APID)+"_"+String(ESP.getChipId(),HEX);
  config.hostName = "arnoldg";
  Portal.config(config);
  Portal.begin();
`
the app runs fine, looks like config.apid can't handel a " " string

**Comment by Hieromon** [comment]
Umm, In my environment, it works well.
Perhaps, is this the same symptom? https://github.com/esp8266/Arduino/issues/2826

**Comment by ageurtse** [comment]
same as isue https://github.com/Hieromon/AutoConnect/issues/35 for me it could be closed.

**Comment by Hieromon** [comment]
Close with issue #35
