### ISSUE TITLE
Automatic switch WIFI

### ISSUE THREAD

**Issue by ddonindia** [Hieromon/AutoConnect#259]
I have two WIFI access points A and B.  First I connected A then B. 
If I restart ESP32 it always try to connect to access point B and if its not available AutoConnect starts in AccessPoint mode.  A access point is always online.

I am using https://github.com/Hieromon/AutoConnect/blob/b79028346eeedf8139b2e50467fbd5a21862bb77/examples/Credential/Credential.ino sketch  with `Config.autoReconnect = true` 

Can you please help ?

**Comment by Hieromon** [comment]
This is strange. If autoReconnect is enabled, AutoConnect will scan the SSID that is being broadcast if the first WiFi.begin fails with the B access point and match it with the stored credentials. At this time, ESP32 should be able to connect to the A access point you mentioned.

Could you please refer to the documentation and enable [**AC_DEBUG**](https://hieromon.github.io/AutoConnect/faq.html#3-turn-on-the-debug-log-options) to get the log?

If you are using the PlatformIO, set **build_flags** in platformio.ini as below:

```ini
build_flags =
  -DCORE_DEBUG_LEVEL=5
  -DAC_DEBUG
```

For the Arduino IDE, edit the library source [**AutoConnectDef.h**](https://github.com/Hieromon/AutoConnect/blob/b79028346eeedf8139b2e50467fbd5a21862bb77/src/AutoConnectDefs.h#L14) directly and uncomment `// #define AC_DEBUG` line. Then specify `Verbose` at the `Core Debug Level:` in the Arduino IDE's Tools menu.

**Comment by ddonindia** [comment]
Thanks I will try and report back.

**Comment by ddonindia** [comment]
After erasing and reflash firmware its started working
