### ISSUE TITLE
AutoReconnect not working

### ISSUE THREAD

**Issue by plusmartin** [Hieromon/AutoConnect#261]
The BSSID credentials are stored but the ESP32 dos not connect back to any of them.
I set:
Config.autoReconnect = true;
and also
WiFi.setAutoReconnect(true);

It wont connect to the stored wifis. If I enter the captive portal I can manually select the BSSID and it works, but it has to do it automatically.

I erased the flash and intalled 1.1.7 Autoconnect.h but it does not work.

**Comment by Hieromon** [comment]
Closed due to same as #251
