### ISSUE TITLE
Unable to change config's default apid & password

### ISSUE THREAD

**Issue by austinhjones** [Hieromon/AutoConnect#266]
Hi, I'm trying to change the default `AutoConnectConfig.apid` and `AutoConnectConfig.psk` so that I can have custom values instead of the defaults of `esp32ap` and `12345678`.

I've tried setting them using the alternate constructor for `AutoConnectConfig` (`AutoConnectConfig config("custom_apid", "custom_psk")`), but that won't work. I've also tried redefining the constants (`AUTOCONNECT_APID` and `AUTOCONNECT_PSK`) that are used to set the default, which also hasn't worked. 

Any tips for setting custom values for username and password?

Thanks.

**Comment by Hieromon** [comment]
If the sketch is correct, it should work. 

```cpp
AutoConnect portal;
AutoConnectConfig config("custom_apid", "custom_psk");

void setup() {
  ...
  portal.config(config);
  portal.begin();
  ...
}
```

Also, How did you try to redefine AUTOCONNECT_APID and AUTOCONNECT_PSK? It has no effect on a compilation for AutoConnect by trying to define it in the sketch.
>  I've also tried redefining the constants (AUTOCONNECT_APID and AUTOCONNECT_PSK) 

You need to modify the library source AutoConnectDefs.h directly or pass the macro definition to the compiler with a parameter as -D. If you're assuming an Arduino IDE, the easiest and surest way is to change the library source.

**Comment by fracland** [comment]
Hi

For me 

```
AutoConnect portal;
AutoConnectConfig config("ap_portal", "new_passwrod");

void setup() {
  portal.config(config);
  portal.begin();
}
```
... is working but ...

```
AutoConnect portal;
AutoConnectConfig config;

void setup() {
  config.apid = "ap_portal";
  config.psk  = "new_password";
  portal.config(config);
  portal.begin();
}
```
... is not working,  the effective apid is a bad string with non ascii character ... 

Thanks for you help.

>

**Comment by Hieromon** [comment]
Closed due to the answer.
