### ISSUE TITLE
DNS troubles when AP_STA mode

### ISSUE THREAD

**Issue by eldiamond2** [Hieromon/AutoConnect#267]
Hello! Here's my issue:
After configuration thru web-browser at _ac/config page, ESP32 stays in APSTA mode.
PubSubClient when trying to connect catch error:
```
Reconnecting to MQTT 
Client id: [%Client-name]
[E][WiFiGeneric.cpp:654] hostByName(): DNS Failed for mqtt.[hostname].com
```
Should mode stay AP_STA? Why AP stay works? Should AC reboot esp when credentials received? How to config it?

Is there any callback when credentials recieved?
I even tried to re-init PubSubClient with 
` mqtt.setClient(client);`

**Comment by Hieromon** [comment]
Use `WiFi.mode(WIFI_STA)` after WiFi client connection established. Generally, it can be determined by the return code of `AutoConnect::begin`.

However, Why does WiFi.hostByName fail in AP_STA mode?
After establishing a connection with the access point as a WiFi client (that is, the IPs have configured), AutoConnect disconnects SoftAP and shuts down the internal DNS server. Does WiFi.hostByName fail in this state?
I tested minimal Sketch using WiFi.hostByName without the pubsubclient, it worked fine.

**Comment by Hieromon** [comment]
Closed as it is not considered to be a library issue.
Post the reduced code which can be reproduced the problem, if necessary.
