### ISSUE TITLE
Unable to cusomize the SSId and PASS

### ISSUE THREAD

**Issue by smithtekIOT** [Hieromon/AutoConnect#278]
Hello.

Great APP! Im not sure it is an issue and more a user error. Im trying to customize the SSId and PASS following the instructions here https://hieromon.github.io/AutoConnect/advancedusage.html#make-ssid-of-softap-unique

IDE wont compile. Can you advise im doing it the right way please?
`#include <ESP8266WiFi.h>          // Replace with WiFi.h for ESP32
#include <ESP8266WebServer.h>     // Replace with WebServer.h for ESP32
#include <AutoConnect.h>

ESP8266WebServer Server;          // Replace with WebServer for ESP32
AutoConnect      Portal;
AutoConnectConfig acConfig;
//AutoConnectConfig(const char* ap, const char* password)
//const char *YOUR_PASSWORD = "12345678";

void setup() {
acConfig.apid = "Custom SSID-" + String(ESP.getChipId(), HEX);
acConfig.psk = YOUR_PASSWORD;
portal.config(acConfig);
portal.begin();
}

void loop() {
    Portal.handleClient();
}`

Im new to C++ so please excuse my inability to figure this out.

Thanks

**Comment by Hieromon** [comment]
Change `AutoConnect Port` to `AutoConenct portal`.
Deifne `YOUR_PASSWORD` you wish.
