### ISSUE TITLE
No output to Monitor and need password for esp32ap

### ISSUE THREAD

**Issue by AdaBill** [Hieromon/AutoConnect#283]
Your program looks very interesting and it would fill my needs, but cannot get it to run completely.
 
Have a ESP32 project and needed to be able to redo the update the SSID and Password if I get a new router.  I installed your program through the Arduino IDE library manager. Installed it and ran it and 1) no output to monitor 2) when I connected to the WiFi scan  esp32ap, it asked for a password. tried 123456789 and several others, NO GO. couldn't log in!

Also, seems like it uses TOO much program space.

here are a some compile notes , Compiler Warnings: ALL,  NO errors!
*************************************
Auto-detected Flash size: 4MB
Chip is ESP32D0WDQ6 (revision 1)
Sketch uses 1193761 bytes (91%) of program storage space. Maximum is 1310720 bytes.
Global variables use 46248 bytes (14%) of dynamic memory, leaving 281432 bytes for local variables. Maximum is 327680 bytes.
*************************************

**Comment by Hieromon** [comment]
Read the [AutoConnect documentation](https://hieromon.github.io/AutoConnect/faq.html#still-not-stable-with-my-sketch) and [a related posted issue](https://github.com/Hieromon/AutoConnect/issues/203) to clarify what you need to do first.
Then we need to determine if the request is worth implementing as a generic library. Implement features that are only convenient for you, by yourself.

Thank you.
