### ISSUE TITLE
Server does not respont after being inactive for a day

### ISSUE THREAD

**Issue by 1JonaB1** [Hieromon/AutoConnect#290]
Hello, Im using the Autoconnect libary in my project on an esp32. I don't know if it is an Feature but after an hour the server takes a while on first use, which would be ok however after a day it doesn't work entirely.

**Comment by Hieromon** [comment]
Can you provide logs with AC_DEBUG enabled?
Follow the documentation, see [here](https://hieromon.github.io/AutoConnect/faq.html#3-turn-on-the-debug-log-options) and [here](https://hieromon.github.io/AutoConnect/faq.html#still-not-stable-with-my-sketch).

**Comment by 1JonaB1** [comment]
Thank you for your answere. Here are my logs:
https://pastebin.com/RnDUNdVq
At the start i needed to connect manualy over the saved networks
At the end i connected to the accespoint again (don't know why)

**Comment by Hieromon** [comment]
AutoAutoConnect appears to be working fine.
