### ISSUE TITLE
How to serve OTA server in raspberry pi 4

### ISSUE THREAD

**Issue by nowzenith** [Hieromon/AutoConnect#309]

**Comment by Hieromon** [comment]
It's no different from the Python environment running on Linux distributions.
The [*updateserver.py*](https://github.com/Hieromon/AutoConnect/tree/master/src/updateserver) script included in the library has been tested on the Raspberry PI 2B.

Mentioning the Raspberry PI or Python environment does not maintain a direct relationship with the AutoConnect library, so close it once.
If necessary, raise the FAQ in Discussions.

**Note:**
There are no open ports on the default configuration of the initial Raspbian. It requires TCP ports where [*http.server*](https://docs.python.org/3.7/library/http.server.html#module-http.server) can transparently communicate with the Internet.
