### ISSUE TITLE
How to recover the STA MAC parameter for use in my scketch?

### ISSUE THREAD

**Issue by joelv1964** [Hieromon/AutoConnect#31]
Hi,

Autoconnect is an excellent library with a great user manual. On behalf of the community : Thank you!

Here is my problem (probably simple, but I can not ...) : I would like to recover the STA MAC parameter for use in my sketch on ESP32. How to recover this value?
If I use STA_MAC in my Sketch, I get the following error message _STA_MAC was not declared in this scope_. I looked in the different files of the directory src, but I don't understand how to pass this parameter in my Sketch.

I have the option to retrieve this setting by using `ESP.getEfuseMac ()`, but STA_MAC is already used by the Autoconnect library (visible on the main menu), and that would simplify my code.
Can you help me please ?

Thank you in advance.
Joel

**Comment by Hieromon** [comment]
The function to obtain the MAC address of STA is `WiFi.macAddress()`.
https://github.com/espressif/arduino-esp32/blob/81844f53600c3035fda6b9affb79c19573ee8f1d/libraries/WiFi/src/WiFiSTA.cpp#L416
AutoConnect uses this function but does not export the result to the global scope as STA_MAC. You will need to use that function yourself.
However, this method is effective only when connected by STA. If you want the MAC address before WiFi.begin() with WIFI_STA is called you need to use SDK natively. You can refer to the topic of the arduino-esp32 core. https://github.com/espressif/arduino-esp32/issues/932
