### ISSUE TITLE
Exemple mqttRSSI_NA it's not working

### ISSUE THREAD

**Issue by DanielSamp4** [Hieromon/AutoConnect#335]
Primeiramente, parabens pelo trabalho,

Mas os exemplos de mqtt da biblioteca, nao estão conseguindo se conectar com o servidor thingspeak.

![img2](https://user-images.githubusercontent.com/56495082/112046484-dac28300-8b2a-11eb-87c8-29dfe461607a.png)
![img3](https://user-images.githubusercontent.com/56495082/112046487-dac28300-8b2a-11eb-8b9a-9b790610ff15.png)
![img1](https://user-images.githubusercontent.com/56495082/112046490-db5b1980-8b2a-11eb-852d-3f16db08972a.png)
![image](https://user-images.githubusercontent.com/56495082/112047120-9d122a00-8b2b-11eb-909d-8197e00ba9f8.png)
![image](https://user-images.githubusercontent.com/56495082/112048424-26762c00-8b2d-11eb-890d-399577deb8f4.png)

I dont know, but i'am putting all the api key's right, but it's not working, kepp printing Connection failed:-2, and this -2 its from PubSubClient::state() and -2 indicates that connection failed.

**Comment by v-c** [comment]
The server for ThingSpeak MQTT is mqtt.thingspeak.com.

**Comment by Hieromon** [comment]
Added a supplementary explanation to correctly set the parameters that give to mqttRSSI.ino for connecting to the MQTT broker serviced by ThingSpeak.
https://hieromon.github.io/AutoConnect/howtoembed.html#sketch-publishes-messages
