### ISSUE TITLE
WebUpdate Show Firmware Version

### ISSUE THREAD

**Issue by lucho512** [Hieromon/AutoConnect#340]
As I can add a label in the webupdate page that indicates the firmware version, this variable would be defined in the main.

Thanks!!!

**Comment by Hieromon** [comment]
@lucho512 
> As I can add a label in the webupdate page that indicates the firmware version,

How?, Which the webupdate page?, Can you offer a concrete way of doing that?

**Comment by lucho512** [comment]
Hi Hieromon,

How can I show the current firmware version on the update page? the idea would be to add an actext in the update page to send the value that contains the firmware version

I hope I have explained myself, my English is poor

Greetings
