### ISSUE TITLE
Proper Web interface (labels) translation

### ISSUE THREAD

**Issue by Warlib1975** [Hieromon/AutoConnect#344]
Hi, 

thank you for the lib. A lot of features. 

Could you give some recommendations on how properly make translation/localization of the AutoConnect lib? You regularly make some significant features addition or bugs fixing and it would be good to have a way not to replace *.h files with translated labels, but override labels in the code, e.g. using ifdef.

**Comment by Hieromon** [comment]
This topic continues in the Discussions.
