### ISSUE TITLE
Trying to establish WiFi connection once after start although immediateStart=true

### ISSUE THREAD

**Issue by danielw63** [Hieromon/AutoConnect#359]
Hi Hieromon, 
thanks for your great library at first.
As you can read in the title I´m trying to achieve that my ESP always enables the captive portal with one addition: the ESP shall not skip the 1st WiFi begin. The idea is that the user always has the option to either connect to the ESPs AP or via the network the ESP is connected to.
I'm using the following settings:
`
Config.autoReconnect = true;
Config.retainPortal = true;
Config.immediateStart = true;
`
My problem is that whenever the ESP is restarted, I have to manually connect it to my network again.
What I´d like to implement is that the ESP restarts, starts the CP and tries to connect to a known network (once).
Is there a way to do this?

**Comment by Hieromon** [comment]
Only enable `config.autoReconnect = true;` and intentionally disconnect WiFi using `WiFi.disconnect(true);` just before `porta.begin()`.
This sequence will always cause the **1st-WiFi.begin** to fail and launch the captive portal if it can't find an AP that it has connected to in the past. If the AP that was connected in the past is found, the reconnection attempt will start by the effect of `AutoConnectConfig::autoReconnect`.

**Comment by danielw63** [comment]
Thank you very much!
This worked for me.
