### ISSUE TITLE
Broken html instead Captive portal

### ISSUE THREAD

**Issue by Evgen2** [Hieromon/AutoConnect#379]
About 4 month ago (at March of 2021) all work well, but now I see this picture instead of Captive portal.
Just test code from  [gettingstarted](https://hieromon.github.io/AutoConnect/gettingstarted.html), HelloWord example, both from Arduino and PlatformIO IDE..

![photo_2021-07-17_11-32-35](https://user-images.githubusercontent.com/11079227/126031274-beb9a1c2-1208-4bf9-9de4-25973968ed3d.jpg)

**Comment by Hieromon** [comment]
Same as #365
