### ISSUE TITLE
Any support for ESP32-C

### ISSUE THREAD

**Issue by efairon** [Hieromon/AutoConnect#387]
Hello,

Do you have any plan to support [ESP32-C3](https://www.espressif.com/en/products/socs/esp32-c3)?

We would love to use AutoConnect with esp32-c3.

**Comment by Hieromon** [comment]
The ESP32-C3 is an SoC with a structure similar to the ESP32-S2, and the core has been replaced with a RISC base, but the ESP-IDF adopts the same programming model in that they are single cores.

So, The version of the Arduino framework for ESP32 that supports these single-core SoCs is 2.0.0 or later. The version of the Arduino framework for ESP32 that supports these single-core SoCs is 2.0.0 or later. The progress of the ESP32 Arduino core is in the pre-release stage of 2.0.0, and AutoConnect has not yet validation.

Same as #223 

<img alt="ESP32-S2_BlockDiagram" src="https://user-images.githubusercontent.com/12591771/127799167-e7d52e11-62dd-46dd-ac6c-4eed390890a8.png" width="480px">

<img alt="ESP32-C3_BlockDiagram" src="https://user-images.githubusercontent.com/12591771/127799174-f90e1076-2da7-42c1-b5c3-92d976dd4801.png" width="480px">
