### ISSUE TITLE
AutoConnect _ac page not working _ac, not saving WiFi credentials 

### ISSUE THREAD

**Issue by gpala7077** [Hieromon/AutoConnect#403]
I've been using AutoConnect for a while and I've loved it. However I've just recently come across an error and I'm not sure what is causing it. I suspect there has been an update on one of the dependencies that is making this happen. 

After flashing my ESP-01 with one of the AutoConnect examples, I flashes fine but when It is plugged into power to connect and configure I receive this when I connect to the esp AP:

`!OTP` tltteAtCnetsaitctlfn-aiyHleiaAilsn-ei;otsz:6x-stx-ieajs:0%-ekttx-ieajs:0%-o-s-otsotiggasae-ektfn-mohn:nilae}oymri:;adn:}bs-ae{agn02p 2x.aepnl*lbl:o(bn)dslyiln-lc;it:.e;etainrgt.aepnl*.ls{it:uofn-ie09mmri-et1p;etainlf}nu{mzapaac:oe-ektapaac:oefn-ie09mmri:p uo.a{iiiiyclas}lptre{iiiiyvsbe.a:agt.vra{pct:.;rniin03}lptre mdlbto{pct:;rniin03}oelptp0lf:;it:0%hih:0%psto:ie;pct:;akrud#0;-ne:00.oa_utnbre-ais1p;akrud#603clr#ffcpdig2p 0xtx-lg:etrtx-eoainnn;etrsaig1xfn-egtbl;ipa:nieboktp4%lf:0;it:0;oiinfxdoaiy0zidx10}al{odrclas:olpebre-pcn:;odr1xsld#d;oo:44bcgon-oo:ffmri-otm2p}al.notbeif>fo,al.notedwdh10;odrclr#CDDtbeif>ha{akrudclr#CDDtbeif>ha>rt{oo:fft,hpdig1p 2xtedbcgon-oo:fff;odrbto:p oi ddtedt>hfn-egt40tx-lg:ettotbre-o:p oi ddtoytoyt:t-hl(d)bcgon-oo:fftoyt>dtott>dfn-egt30fn-ie.8mtoyt:t-hl(vn{akrudclr#777tbeif bd>rnhcidee)bcgon-oo:EFF}l-ie{it:0%psto:ie;o:;et0zidx10;o-hdw01x3xrb(,0 ,01) p p ga0 ,0 .4}l-ugrsa,l-ugrsa:bfr,l-ugrsa:atrdslybokhih:p;it:6xtasto:.ses}l-bcekd.bmn i.bbre pnbcgon-oo:rnprn}l-bcekd.bmn i.bbre pn:eoe.bc:hce~l-eul l-ugrsa:atrmri-o:}l-edrdslyfe;lxdrcinrwjsiycnetsaebtenainiescne;egt5p}l-eurgt.bbre{agnlf:uo.bbadfn-ie16mpdig1p 4x1p 4x.bmn{i-egt5p;rniin06 aewdh10}l-aiaindslyfe;lxdrcinclm;itsyenn;adn-et0mri:}l-eua.bie {etdcrto:oeclrihrtcro:one}l-tmhih:8x.bie {adn:8x2p 8x2p;ipa:lc}l-ugrpdig1p 4x1p 4xpsto:eaiecro:one}l-ugrsa:bfr,l-ugrsa:atrcnet';oiinaslt}l-ugrsa:bfr{agntp-p}l-ugrsa:atrmri-o:p}l-bdslynn}l-bnt:hce).bmn{vrlwhde;egt5p}l-bcekd.bmn{rniinhih .ses;egt10hoefo:uo.rponpsto:eaiehih:uomnhih:8x.rponhvru{oiinrltv;ipa:lc;i-it:0%.rpona:fe{oiinaslt;otn:'rgt1p;o:5xbre-it:p p ;odrclrtasaetbre-tl:oi}dodw>ldslybokoefo-:idnls-tl:oepdig0.rponu l-tmmnwdh10;egt2p;adn:p 0x5x4p}dodw>l.bie {i-egt2p;iehih:9xpdig0@ei cenad(i-it:6p).bnvgto{lxfo:o;utf-otn:lxed}l-ugrdslynn;.bc:o(cekd~l-euoefo:iil;.bc:hce~l-euhih:8x}l-eu.bie{odrtp0}l-eurgt.bhae{agnrgtat;.rponhih:8x}dodw:oe>lpsto:bouelf:;o:8xpdig0}dodw>ldslynn;.rponu l-tmpdig5x1p;.rponu l-tmawiesaenwa;}l-bcekd.bmn l-ugrdlpnsa:bfr{rnfr:oae25e).bc:hce+l-eu.bbre-bsi pn:fe{rnfr:oae-2dg}l-eumtra,l-eumtra dodw lbcgon-oo:233;oo:ff.bmn-aeil.cie.bmn-aeil.bie:oe{akrudclr#77f.bmn-aeil.bbre pn.bmn-aeil.bbre pn:eoe.bmn-aeil.bbre pn:fe{akrudclr#f}/tl>/edhae d"b ls=l-ie"dvcas"bmn bmn-ih bmn-aeil>u ls=l-aiain>l ls=l-edr>ahe=/a"cas"bbad>uoonc/ae>/il ls=l-tm>ahe=/a/pn>pnSIs/>/il ls=l-tm d"ee"< rf"rl"Rst.l ls=l-tm>ahe=/ieoe>ieoe/>/i/lahe=#ee"cas"vra"/2dvtoyt>hMti/rt>T()/dt>t>P/d/rt>9.6.01/dt>t>untmst>5.5.5./r/rt>6E:D4:AE/rt>t>hnet>/rt>t>hpIt>547/rt>t>ls `ie/dt>t>remmrt>40/r/tlÿ`

When I navigate to another page such as `http://espIP/_ac/config` I am directed to the normally formatted page where I can select the WiFi network, and once I connect to the WiFi Network it doesn't seem to save it when it resets and I'd have to configure the esp all over again by navigating to http://espIP/_ac/config manually and connecting to a WiFi network.

This just started happening and I'm not sure what is going on. It seems it is only the _ac page that is the problem. Perhaps something with PageBuilder?

**Comment by Hieromon** [comment]
If you experience symptoms like the one you posted after updating the Arduino core for ESP8266 3.0.0, it's because the AutoConnect version and an arduino core are inconsistent. AutoConnect does not support ESP8266 Arduino Core 3.0.0 yet.
Currently, the latest AutoConnect and PageBuilder are staged in the development branch. Use the development branch version to try out the latest Arduino core.

AutoConnect v1.3.0 ESP8266 3.0.0 later or ESP32 2.0 later supported: Branch [enhance/v130](https://github.com/Hieromon/AutoConnect/tree/enhance/v130)
PageBuilder v1.5.0 ESP8266 3.0.0 later or ESP32 2.0 later supported: Branch [enhance/v150](https://github.com/Hieromon/PageBuilder/tree/enhance/v150)
