### ISSUE TITLE
Adding requrements or submodules to your Projekt

### ISSUE THREAD

**Issue by 8bignic8** [Hieromon/AutoConnect#428]
hey you could add submodules to your Projekt, so everyone who is donloading your Library gets also the other requred ones :).

git submodule add https://github.com/Hieromon/PageBuilder
git submodule add https://github.com/bblanchon/ArduinoJson

Tanks for writing the AutoConnect Library :)

**Comment by Hieromon** [comment]
I can't accept it now.
I'm the only one who manages the release of PageBuilder. PageBuilder may enhance independently and may add experimental features to the point of breaking backward compatibility. In that case, PageBuilder temporarily loses its interface with AutoConnect, but the commit does not release and only advances the master branch. It is possible to determine the version of PageBuilder that is consistent with AutoConnect as a submodule, but adding it is virtually the same as controlling the version by the library property. AutoConnect is released after the version matches with PageBuilder.
ArudinoJson The same can be said at any time.
Sorry for your inconvenience., please use the library manager of Aurora IDE or the PIO library repository.
