### ISSUE TITLE
how to change the Soft ap user name and password

### ISSUE THREAD

**Issue by Mrtian2** [Hieromon/AutoConnect#44]
Hi sorry may I as you how to change this sentence 

[AC] SoftAP esp32ap/12345678 Ch(1) IP:192.168.244.1 

the wifi  name as   "esp32ap and password   12345678"  can I change the name and the password ?

**Comment by Hieromon** [comment]
You can change both by setting [AutoConnectConfig::apid](https://hieromon.github.io/AutoConnect/apiconfig.html#apid) and [AutoConnectConfig::psk](https://hieromon.github.io/AutoConnect/apiconfig.html#psk).
I was leaking commentary on it from the documentation and have already revised. Refer to chapter [Change SSID and Password for SoftAP](https://hieromon.github.io/AutoConnect/advancedusage.html#change-ssid-and-password-for-softap) in the [Documentation](https://hieromon.github.io/AutoConnect).
