### ISSUE TITLE
send value to custom config page as initial values.

### ISSUE THREAD

**Issue by ageurtse** [Hieromon/AutoConnect#46]
hi Hieromon,

i can't make a sence on hot to set the initial values on a custom config page.

this is what i have so var:
```
// Loading from PROGMEM
const char settings[] PROGMEM = R"raw(
{
  "title" : "Dimmer Settings",
  "uri" : "/Settings",
  "menu" : true,
  "element" : [
    {
      "name" : "caption",
      "type" : "ACText",
      "value" : "Dimmer settings"
    },
    { "name" : "Dimvalue1",
      "type" : "ACInput",
      "value" : "10",
      "pattern": "^[0-6]?[0-9]$",    //review
      "label" : "Minimum dimvalue"
    },
    {
      "name": "save",
      "type": "ACSubmit",
      "value": "Save",
      "uri": "/saveDim"
    }
  ]
}
`)raw";
```

and this is my variable to send to the page 
  byte minDimValue;

this is in my setup
```
  portal.load(settings);
  portol.on("/Settings",settingsOn, AC_EXIT_AHEAD);   //is this right, and how should settingsOn look like
  portal.config(config);
```

**Comment by ageurtse** [comment]
seems that i have found a way.
```
  AutoConnectInput& Dimvalue1 = aux.getElement<AutoConnectInput>("Dimvalue1");
  // Set initial value for the input box in a custom Web page.
  Dimvalue1.value = "25";
  // Nothing appendix for a generated HTML.
  return String();
```

now i which to know is there a one line solution to set the value ?

**Comment by ageurtse** [comment]
by the way, when in github on the readme clicking on a link to the documentation sometimes i get a 404 error, it looks like there is somthing wrong with the links.

**Comment by Hieromon** [comment]
@ageurtse 
> now i which to know is there a one line solution to set the value ?

Basically, your method is correct for setting the initial value.
Alternatively, you can use the [setElementValue](https://hieromon.github.io/AutoConnect/apiaux.html#setelementvalue) function.

```cpp
String settingsOn(AutoConnectAux& aux, PageArgument& args) {
  aux.setElementValue("Dimvalue1", "25");
  return String();
}
```

**Comment by Hieromon** [comment]
> sometimes i get a 404 error, it looks like there is somthing wrong with the links.

Thank you!, I missed it and fixed it.
