### ISSUE TITLE
error when disabeling debug

### ISSUE THREAD

**Issue by ageurtse** [Hieromon/AutoConnect#49]
Hi Hieromon, 

when commenting out AC_DEBUG in AutoConnectDefs.h i get an error. 
The error is in file AutoConnectEllementBasisImpl.h on line 86 you have AC_DEBUG this should be AC_DBG

after changing the file is compiling, please update this little bug.

**Comment by Hieromon** [comment]
Oops! I forgot to build test after disabling AC_DEBUG before release.
Thank you for finding it. @ageurtse 
Since this is fatal, I will change the master soon.
