### ISSUE TITLE
Turning off the AP

### ISSUE THREAD

**Issue by cruizg** [Hieromon/AutoConnect#5]
When the device (esp8266) has already connected to the Wi-Fi network, the AP mode should be turned off, since some intruder could connect to the AP and change the configuration of the device (Esp8266).
When the key has been changed in the modem the AP should start again in order to update the key and after the connection is established it should be switched off again

**Comment by Hieromon** [comment]
Hello, cruizg

I was reviewing your enhancement request few days, but there is a point as not well for me.
AutoConnect has established a connection once, it will not be in AP mode after the second time for the same access point in the WLAN. However, it is necessary to reset the module from AutoConnect menu or manually.
And if the key of the access point saved previously by ESP8266 has been changed, start AP mode appears in association with STA mode. This is such the specification of AutoConnect current version.
Is your request different from this behavior?

**Comment by cruizg** [comment]
yes , is correct.

**Comment by Hieromon** [comment]
I supported the option to reconnect to a known access point in conjunction with issue #6.
This feature might be useful for your situations. Pls refer https://hieromon.github.io/AutoConnect/advancedusage/index.html#automatic-reconnect.

**Comment by Hieromon** [comment]
Did the problem be solved by the support of AutoReconnect function?
If so, please close this issue.

**Comment by Hieromon** [comment]
Since there was no response even after one month passed, closed this issue as enhanced.
