### ISSUE TITLE
Path traversal vulnerability in `updateserver.py`

### ISSUE THREAD

**Issue by maxbergmark** [Hieromon/AutoConnect#526]
There is currently no protection against path traversal in the `updateserver.py` script. The following URI provides an example of path traversal:

    /_catalog?op=list&path=../..

Anyone hosting this server script and exposing it to the web might become vulnerable. Here's a proposal for how this vulnerability can be patched (I haven't tested the code myself yet):

    if op == 'list':
        try:
            path = urllib.parse.parse_qs(query)['path'][0]
        except KeyError:
            path = '.'
        full_path = os.path.join(self.catalog_dir, path)
        if os.path.commonprefix((os.path.realpath(full_path), self.catalog_dir)) == self.catalog_dir: 
            self.__send_dir(full_path)
            result = True
        else:
            err = 'Path traversal detected'
            result = False
    else:
        err = '{0} unknown operation'.format(op)
        result = False

**Comment by Hieromon** [comment]
@maxbergmark Thank you for your suggestion. As you noted, this script is vulnerable. The following is a quote from the [AutoConnect documentation](https://hieromon.github.io/AutoConnect/otaserver.html#update-server-for-the-autoconnectupdate-class).

> The updateserver.py script equips only the minimum facility because it assumes a private small OTA platform without identifying individual modules and To operate a larger OTA platform, it is necessary to identify the individual ESP module and to consider version control and security.

I would hate to think that updateserver.py will be used as is as a full-fledged update server, but at the very least, it should be considered. I will incorporate your suggestion in the next update turn.

Thank you for your contribution.
