### ISSUE TITLE
error when delete a unique_ptr when hierarchical inheritance c++

### ISSUE THREAD

**Issue by SRAWAS** [Hieromon/AutoConnect#527]
Hello,

I have a problem in memory when delete unique_ptr at the end of scope.

I have a base class :

class Base(){
std::string name;
virtual void create() {};
public :
virtual ~Base() { }
};

I have a first derived class with its own data member

class Derived1: public Base{
std::string m_powerUnit;
DllExport void create() override;
public :
virtual ~Derived1() { }
};

And a second derived class with its own data member:

class Derived2: public Base{
std::vector<uint8_t> m_key;
protected:
DllExport void create() override;
public :
virtual ~Derived2() { }
};

I have a class FF that inherits from Base with its data member :
class FF: public Base{
double m_multiplier;
void create() override;
};
void FF::create() {…}

I have a class WW that inherits from Derived1:

class WW: public Derived1{
…
};

in main, in case of new FF, at the end of scope when delete unique ptr that works !
{
…

std::unique_ptr<Foo> rs = std::unique_ptr<Foo>(new Foo(… FF …));
rs->create();
…

}// the end of scope

but in case of new WW, at the end of scope when delete unique ptr, it does not work, that crash with “HEAP CORRUPTION DETECTED: after Normal block (#1615) at 0x0000021E8E42BE00.
CRT detected that the application wrote to memory after end of heap buffer.”

{
…

std::unique_ptr<Foo> rs = std::unique_ptr<Foo>(new Foo(… WW …));
rs->create();
…

}// the end of scope

To compare FF and WW, FF inherits base class and it has its own data member but WW inherits Derived1 that have a parameter “m_power_unit” and by his turn Derived1 inherits Base class.

When i delete the parameter “m_power_unit” in Derived1 class that works !! but it does not work when Derived1 class has its own data  members or when Derived2 class has its own data members.

It works if class Derived1 does not have its own data members !

Any suggestions please ?

**Comment by Hieromon** [comment]
@SRAWAS, Are you in the wrong repository for your submission?

**Comment by Hieromon** [comment]
This topic is not appropriate as an issue to AutoConnect and is closed.
