### ISSUE TITLE
spam

### ISSUE THREAD

**Issue by svdrummer** [Hieromon/AutoConnect#550]
I keep getting spam sex emails from this repository. Anyone know how to stop that without un-sup from this repository?

**Comment by Hieromon** [comment]
@svdrummer 

Attackers use Discussions mentions as a springboard to spread spam. The damage is widespread, not just to this repository. Several comments were also dropped on the AutoConnect repository. They were all forwarded by Mention.

Several comments were also dropped on the AutoConnect repository. They were all forwarded by Mention. The attack uses multiple GitHub accounts and a script to drop comments on a regular cycle. I confirmed.

I have already reported it to the GitHub Trust & Safety Team and they have taken prompt action. At present, the attacks appear to have temporarily ceased but may resume.

The only measure I can take is to restrict posting from the most recently registered accounts. However, that would limit questions and PR from other regular users. So I will see how it goes for now.
