### ISSUE TITLE
Using Ota Web Browser and Update Server at the same time

### ISSUE THREAD

**Issue by askiin35** [Hieromon/AutoConnect#582]
Hello, I want to use it on the server and browser in the ota part. But there are two updates in the menu and it's routing the update through the server in both menus. Is it possible to use two ota features at the same time? It doesn't work even though I replace the links with defs. Kind regards.

**Comment by Hieromon** [comment]
AutoConnectOTA inherits the structure of ArduinoOTA, while AutoConnectUpdate inherits the structure of HTTPUpdate of the core library. Even if the upload request URLs are separated, they cannot coexist. As far as I know, the WebServer library does not allow them to coexist.
