### ISSUE TITLE
Mqtt Example

### ISSUE THREAD

**Issue by Lordcybertracker** [Hieromon/AutoConnect#600]
Hello,
is there an example ao that Mqtt is already integrated?

Because I would like to use this for my project.
Thanks

**Comment by Hieromon** [comment]
mqtt example is [here](https://github.com/Hieromon/AutoConnect/tree/master/examples/mqttRSSI).
Documentation is [here](https://hieromon.github.io/AutoConnect/howtoembed.html#used-with-mqtt-as-a-client-application).

**Comment by elzershark** [comment]
> Ein MQTT-Beispiel finden Sie [hier](https://github.com/Hieromon/AutoConnect/tree/master/examples/mqttRSSI) . Die Dokumentation finden Sie [hier](https://hieromon.github.io/AutoConnect/howtoembed.html#used-with-mqtt-as-a-client-application) .

Wo ist da eine Anleitung wie man mqtt Zugangsdaten daten eingibt? Sehe ich dort nirgends. Zugangsdaten für mqtt bestehen aus ip Adresse, port, username und passwort. Und das ist nirgends erklärt, wie man das macht. Nur ganz komische mqtt anbieter, die niemand kennt, wo man komische id's und so weiter eingeben soll. Das hat nichts mit mqtt Einstellungen zu tun. Wieder ein script, was keinerlei Funktion hat und überhaupt nichts mit mqtt Daten zu tun hat
