### ISSUE TITLE
Using "AutoConnectCore.h" header and running into errors

### ISSUE THREAD

**Issue by MudassirTufail** [Hieromon/AutoConnect#601]
Hello
I followed the instructions on "Reducing Binary Size" at https://hieromon.github.io/AutoConnect/basicusage.html and switched to using #include <AutoConnectCore.h>, but running into errors below:  [no errors as I switch back to using #include <AutoConnect.h>]. Could you please advise, thank you 

Compiling .pio\build\esp32doit-espduino\lib1c8\AutoConnect\AutoConnectUpdate.cpp.o
.pio/libdeps/esp32doit-espduino/AutoConnect/src/AutoConnectOTA.cpp:19:10: fatal error: Update.h: No such file or directory

****************************************************************
* Looking for Update.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Update.h"
* Web  > https://registry.platformio.org/search?q=header:Update.h
*
****************************************************************

 #include <Update.h>
          ^~~~~~~~~~
compilation terminated.
In file included from .pio/libdeps/esp32doit-espduino/AutoConnect/src/AutoConnectUpdate.cpp:16:
.pio/libdeps/esp32doit-espduino/AutoConnect/src/AutoConnectUpdate.h:44:10: fatal error: HTTPClient.h: No such file or directory

********************************************************************
* Looking for HTTPClient.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:HTTPClient.h"
* Web  > https://registry.platformio.org/search?q=header:HTTPClient.h
*
********************************************************************

 #include <HTTPClient.h>
          ^~~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\esp32doit-espduino\lib1c8\AutoConnect\AutoConnectOTA.cpp.o] Error 1
*** [.pio\build\esp32doit-espduino\lib1c8\AutoConnect\AutoConnectUpdate.cpp.o] Error 1
In file included from .pio/libdeps/esp32doit-espduino/AutoConnect/src/AutoConnectExt.hpp:24,
                 from .pio/libdeps/esp32doit-espduino/AutoConnect/src/AutoConnectConfigAux.h:20,
                 from .pio/libdeps/esp32doit-espduino/AutoConnect/src/AutoConnectConfigAux.cpp:14:
.pio/libdeps/esp32doit-espduino/AutoConnect/src/AutoConnectUpdate.h:44:10: fatal error: HTTPClient.h: No such file or directory

********************************************************************
* Looking for HTTPClient.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:HTTPClient.h"
* Web  > https://registry.platformio.org/search?q=header:HTTPClient.h
*
********************************************************************

 #include <HTTPClient.h>
          ^~~~~~~~~~~~~~
In file included from .pio/libdeps/esp32doit-espduino/AutoConnect/src/AutoConnectExt.hpp:24,
                 from .pio/libdeps/esp32doit-espduino/AutoConnect/src/AutoConnectAux.cpp:10:
.pio/libdeps/esp32doit-espduino/AutoConnect/src/AutoConnectUpdate.h:44:10: fatal error: HTTPClient.h: No such file or directory

********************************************************************
* Looking for HTTPClient.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:HTTPClient.h"
* Web  > https://registry.platformio.org/search?q=header:HTTPClient.h
*
********************************************************************

 #include <HTTPClient.h>
          ^~~~~~~~~~~~~~
compilation terminated.
compilation terminated.
*** [.pio\build\esp32doit-espduino\lib1c8\AutoConnect\AutoConnectAux.cpp.o] Error 1
*** [.pio\build\esp32doit-espduino\lib1c8\AutoConnect\AutoConnectConfigAux.cpp.o] Error 1
================================================================================== [FAILED] Took 21.87 seconds ==================================================================================

**Comment by Hieromon** [comment]
This occurs when [PIO Library Finder](https://docs.platformio.org/en/latest/librarymanager/ldf.html#library-dependency-finder-ldf) does not select the appropriate include headers; **without** [`lib_ldf_mode`](https://docs.platformio.org/en/latest/projectconf/sections/env/options/library/lib_ldf_mode.html#lib-ldf-mode) or **no** `deep`/`deep+`, PIO obtains the necessary include headers resulting from static code analysis but does not evaluate the preprocessor directives recursively. Therefore, source files based on all the include headers detected by PIO's pre-build scan are targets for compilation. This is why you got an error trying to compile AutoConnectAux.cpp even though your build target is <AutoConnectCore.h>.

To fix, specify `lib_ldf_mode = deep` or `deep+` with `pio.ini`.
Since this instruction way is missing from the description of the AutoConnect documentation, I will add it.

**Comment by MudassirTufail** [comment]
Thank You 
I used lib_ldf_mode = deep+ in platform.ini file and that worked.
