### ISSUE TITLE
Notice for the update feature planned in v1.0.0

### ISSUE THREAD

**Issue by Hieromon** [Hieromon/AutoConnect#62]
To all contributors and Users,

Thank you for your interest in AutoConnect. I prepared for the prototype of the update server and application sketch which for sketch binary updating via OTA. I will implementation for v0.99 based on this prototype and will also add automatic updates by version level according to each device. 
The OTA update feature will be incorporated by only one parameter with AutoConnectConfig.
Related issue #26 #50

Please evaluate this prototype if you can and post any comments if you have any requirements that I need to consider for implementation.

The following menu is in interactive mode. In automatic update mode, it will behave in the background.

![update_catalog](https://user-images.githubusercontent.com/12591771/56580387-6b297d80-660d-11e9-9245-e2ed8f694dd9.png) ![update_during](https://user-images.githubusercontent.com/12591771/56580398-6ebd0480-660d-11e9-83b9-46f00429e0a1.png) ![update_restart](https://user-images.githubusercontent.com/12591771/56580413-74b2e580-660d-11e9-915b-ec3f68272502.png)

**Comment by Hieromon** [comment]
Defer this feature enhancement and give priority to esp8266 core 2.5.2 support.
The release of the update feature is expected to be v0.9.10 or later.

**Comment by huexpub** [comment]
maybe  esp32 ota feature ？ i add with autoconnect it crash.....

**Comment by Hieromon** [comment]
The commit section of the development branch is unstable. It does not always work.
It should work with resources staged to the development branch currently and has already implemented most of the above update features.
You can try with the Update.ino example and updateserver.py script included in the resources of the development branch

**Comment by Hieromon** [comment]
The update feature will be released next update turn as v1.0.0.
This topic title changed.
Development branch continues to use [Enhance/v099](https://github.com/Hieromon/AutoConnect/tree/Enhance/v099).
