### ISSUE TITLE
acInput labels

### ISSUE THREAD

**Issue by smiley561** [Hieromon/AutoConnect#72]
Labels of acInput are sometimes above- and at other times left of the input. It would be nice too, if you could arrange them above for aligning.

![ACInputLabels](https://user-images.githubusercontent.com/10628986/57461399-3b1de380-7277-11e9-8a41-1a0817b2ef71.png)

**Comment by Hieromon** [comment]
@smiley561 Thank you for your reports. It is not my intention to wrap the label and the input box. A style sheet is incorrect.
Fixed the master. Please confirm it.

**Comment by smiley561** [comment]
Good work!!!
