### ISSUE TITLE
main menu colors

### ISSUE THREAD

**Issue by smiley561** [Hieromon/AutoConnect#73]
Is it possible to change text/background colors of the main menu?

**Comment by Hieromon** [comment]
I made it possible to customize menu text/background color statically. You can update your AutoConnect library with the latest commit on the master to use color customization.
The menu color scheme has been separated to [`AutoConnectLabels.h`](https://github.com/Hieromon/AutoConnect/blob/master/src/AutoConnectLabels.h). You can change the color scheme of the menu with the following three color codes. The color code also accepts CSS standard color names.

- #define AUTOCONNECT_MENUCOLOR_TEXT
  Defines the menu text color.
https://github.com/Hieromon/AutoConnect/blob/779bd164223ca8b4c20b3a65453c27c822d7329d/src/AutoConnectLabels.h#L74

- #define AUTOCONNECT_MENUCOLOR_BACKGROUND
  Defines the menu background color.
https://github.com/Hieromon/AutoConnect/blob/779bd164223ca8b4c20b3a65453c27c822d7329d/src/AutoConnectLabels.h#L80

- #define AUTOCONNECT_MENUCOLOR_ACTIVE
  Defines the active menu item background color.
https://github.com/Hieromon/AutoConnect/blob/779bd164223ca8b4c20b3a65453c27c822d7329d/src/AutoConnectLabels.h#L86

I'll pick up some color schemes.

### Indigo
```cpp
#define AUTOCONNECT_MENUCOLOR_TEXT        "#ffa500"
#define AUTOCONNECT_MENUCOLOR_BACKGROUND  "#1a237e"
#define AUTOCONNECT_MENUCOLOR_ACTIVE      "#283593"
```
![ACMenu_indigo](https://user-images.githubusercontent.com/12591771/57544048-259cdc80-7391-11e9-8330-6385868ff0a0.png)

### Dimgray
```cpp
#define AUTOCONNECT_MENUCOLOR_TEXT        "#fffacd"
#define AUTOCONNECT_MENUCOLOR_BACKGROUND  "#696969"
#define AUTOCONNECT_MENUCOLOR_ACTIVE      "#808080"
```
![ACMenu_dimgray](https://user-images.githubusercontent.com/12591771/57544220-abb92300-7391-11e9-962a-559a496e71e0.png)

### Brown
```cpp
#define AUTOCONNECT_MENUCOLOR_TEXT        "#e6e6fa"
#define AUTOCONNECT_MENUCOLOR_BACKGROUND  "#3e2723"
#define AUTOCONNECT_MENUCOLOR_ACTIVE      "#4e342e"
```
![ACMenu_brown](https://user-images.githubusercontent.com/12591771/57544224-b07dd700-7391-11e9-8caa-ba5d950e5e89.png)

**Comment by smiley561** [comment]
![Menuitems](https://user-images.githubusercontent.com/10628986/57567693-805c2580-73dd-11e9-8927-66fe9e7e1c15.png)

Nice thing but not all items have changed their color.

**Comment by Hieromon** [comment]
I cannot reproduce. iOS Safari is Ok, Chrome is Ok, MS Edge is Ok.
Are some extensions affect to this phenomenon?

**Comment by smiley561** [comment]
Sorry, it was an addon for changing colors of visited pages.
