### ISSUE TITLE
How to save and load ACSelcect Element

### ISSUE THREAD

**Issue by rueni73** [Hieromon/AutoConnect#81]
Hi,

i build a Custompage by using json with ACInnputs and  ACSelect Elements. 
The ACInputs where saved normaly. 
How can i save the ACSelect and also reload it.

Thx

**Comment by Hieromon** [comment]
Same as Issue #64. Try again using release v0.9.9.
If the problem occurs in v0.9.9 too, please refer to [this guide](https://hieromon.github.io/AutoConnect/faq.html#4-reports-the-issue-to-autoconnect-github-repository) and provide me the information to reproduce and diagnose the problem.

**Comment by Hieromon** [comment]
Since there was no response even after one month passed, closed this issue.
When some reports are posted, reopen it.
