### ISSUE TITLE
HTML using toggle switch

### ISSUE THREAD

**Issue by destiny2008git** [Hieromon/AutoConnect#87]
hi i have this code how do i incorporate the autoconnect to work with this, appreciated:
`#include <ESP8266WiFi.h>

const char* ssid = "Secu";
const char* password = "alpha3";
WiFiServer server(80);
String HTTP_req;          // stores the HTTP request
boolean LED_status = 0;   // state of LED, off by default

void setup()
{
  Serial.begin(74880);
  WiFi.begin(ssid, password);             // Connect to the network
  Serial.print("Connecting to ");
  Serial.print(ssid); Serial.println(" ...");

  int i = 0;
  while (WiFi.status() != WL_CONNECTED) { // Wait for the Wi-Fi to connect
    delay(1000);
    Serial.print(++i); Serial.print(' ');
  }
  // for diagnostics
  pinMode(2, OUTPUT);       // LED on pin 2
  Serial.println("Connection established!");
  Serial.print("IP address:\t");
  Serial.println(WiFi.localIP());         // Send the IP address of the ESP8266 to the computer
  server.begin();
}

void loop()
{
  WiFiClient client = server.available();  // try to get client

  if (client) {  // got client?
    boolean currentLineIsBlank = true;
    while (client.connected()) {
      if (client.available()) {   // client data available to read
        char c = client.read(); // read 1 byte (character) from client
        HTTP_req += c;  // save the HTTP request 1 char at a time
        // last line of client request is blank and ends with \n
        // respond to client only after last line received
        if (c == '\n' && currentLineIsBlank) {
          client.println("HTTP/1.1 200 OK");
          client.println("Content-Type: text/html");
          client.println("Connection: close");
          client.println();
          // send a standard http response header
          client.println("<!DOCTYPE html>");
          client.println("<html>");
          client.println("<head>");
          client.println("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>");
          client.println("<title>");
          client.println("SmartHome LED Control");
          client.println("</title>");
          client.println("</head>");
          client.println(" <style>    ");
          client.println("   .onoffswitch {");
          client.println("        position: relative; width: 191px;");
          client.println("        -webkit-user-select:none; -moz-user-select:none; -ms-user-select: none;");
          client.println("    }");
          client.println("    .onoffswitch-checkbox {");
          client.println("        display: none;");
          client.println("    }");
          client.println("    .onoffswitch-label {");
          client.println("        display: block; overflow: hidden; cursor: pointer;");
          client.println("        border: 2px solid #999999; border-radius: 50px;");
          client.println("    }");
          client.println("    .onoffswitch-inner {");
          client.println("        display: block; width: 200%; margin-left: -100%;");
          client.println("        transition: margin 0.3s ease-in 0s;");
          client.println("    }");
          client.println("    .onoffswitch-inner:before, .onoffswitch-inner:after {");
          client.println("        display: block; float: left; width: 50%; height: 75px; padding: 0; line-height: 75px;");
          client.println("        font-size: 34px; color: white; font-family: Trebuchet, Arial, sans-serif; font-weight: bold;");
          client.println("        box-sizing: border-box;");
          client.println("    }");
          client.println("    .onoffswitch-inner:before {");
          client.println("        content: \"ON\";");
          client.println("        padding-left: 14px;");
          client.println("        background-color: green; color: white; //ON Colors");
          client.println("    }");
          client.println("    .onoffswitch-inner:after {");
          client.println("        content: \"OFF\";");
          client.println("        padding-right: 14px;");
          client.println("        background-color: red; color: white;");
          client.println("        text-align: right;");
          client.println("    }");
          client.println("    .onoffswitch-switch {");
          client.println("        display: block; width: 50px; margin: 12.5px;");
          client.println("        background: grey;");
          client.println("        position: absolute; top: 0; bottom: 0;");
          client.println("        right: 112px;");
          client.println("        border: 2px solid yellow; border-radius: 50px;");
          client.println("        transition: all 0.3s ease-in 0s; ");
          client.println("    }");
          client.println("    .onoffswitch-checkbox:checked + .onoffswitch-label .onoffswitch-inner {");
          client.println("        margin-left: 0;");
          client.println("    }");
          client.println("    .onoffswitch-checkbox:checked + .onoffswitch-label .onoffswitch-switch {");
          client.println("        right: 0px; ");
          client.println("        background-color: grey; ");
          client.println("    }");
          client.println("</style>");
          client.println("<body>");
          client.println("<form method=\"get\">");
          client.println("<div class=\"onoffswitch\">");
          ProcessCheckbox(client);
          client.println("<label class=\"onoffswitch-label\" for=\"myonoffswitch\">");
          client.println("<span class=\"onoffswitch-inner\"></span>");
          client.println("<span class=\"onoffswitch-switch\"></span>");
          client.println("</label>");
          client.println("</div>");
          //client.println("<label class=\"toggle\">");
          //client.println("<span class=\"slider\"></span>");
          //client.println("</label>");
          client.println("</form>");
          client.println("</body>");
          client.println("</html>");
          Serial.print(HTTP_req);
          HTTP_req = "";    // finished with request, empty string
          break;
        }
        // every line of text received from the client ends with \r\n
        if (c == '\n') {
          // last character on line of received text
          // starting new line with next character read
          currentLineIsBlank = true;
        }
        else if (c != '\r') {
          // a text character was received from client
          currentLineIsBlank = false;
        }
      } // end if (client.available())
    } // end while (client.connected())
    delay(1);      // give the web browser time to receive the data
    client.stop(); // close the connection
  } // end if (client)
}

// switch LED and send back HTML for LED checkbox
void ProcessCheckbox( WiFiClient cl)
{
  if (HTTP_req.indexOf("onoffswitch=2") > -1)
  { // see if checkbox was clicked
    // the checkbox was clicked, toggle the LED
    if (LED_status)
    {
      LED_status = 0;
    }
    else
    {
      LED_status = 1;
    }
  }

  if (LED_status)
  { // switch LED on
    digitalWrite(2, HIGH);
    // checkbox is checked
    //cl.println("<div style=\"font-size: 80px\">");
    //cl.println("<label class=\"toggle\">");
    cl.println("<input type=\"checkbox\" name=\"onoffswitch\" class=\"onoffswitch-checkbox\" id=\"myonoffswitch\" value=\"2\" onclick=\"submit();\" checked>");
    //cl.println("<span class=\"slider\"></span>");
    //cl.println("</label>");
    //cl.println("</div>");

  }
  else {// switch LED off
    digitalWrite(2, LOW);
    // checkbox is unchecked
    //cl.println("<div style=\"font-size: 80px\">");
    //cl.println("<label class=\"toggle\">");
    cl.println("<input type=\"checkbox\" name=\"onoffswitch\" class=\"onoffswitch-checkbox\" id=\"myonoffswitch\" value=\"2\" onclick=\"submit();\" >");
    //cl.println("<span class=\"slider\"></span>");
    //cl.println("</label>");
    //cl.println("</div>");
  }
}`

**Comment by Hieromon** [comment]
At first, port your sketch to work with the ESP8266WebServer library.
Next, implement the submit button handler. The handler controls the LED blink with digitalWrite. Also, to indicate the ON/OFF status on a web page, send out a style class attached to it.

I already provide an example using AutoConnect that works similar to your sketch. The explanation for these examples is available on the [documentation](https://hieromon.github.io/AutoConnect/howtoembed.html).

1. [HandleClient](https://github.com/Hieromon/AutoConnect/blob/master/examples/HandlePortal/HandlePortal.ino) as an example uses a clichéd way.
2. [HanlePortalEx](https://github.com/Hieromon/AutoConnect/blob/master/examples/HandlePortalEX/HandlePortalEX.ino) as an example demonstrates how to generate web pages smarter way than the HandlePortal using the [PageBuilder](https://github.com/Hieromon/PageBuilder).

If you want to put out the LED ON/OFF control page itself as a custom web page, you can use [AutoConnectElement](https://hieromon.github.io/AutoConnect/acelements.html#autoconnectelement-a-basic-class-of-elements) and [AutoConnectSubmit](https://hieromon.github.io/AutoConnect/acelements.html#autoconnectsubmit). The entity of the ON/OFF button on the web page is actually coded with a style class, so it can be stored in the [value](https://hieromon.github.io/AutoConnect/acelements.html#value) attribute of AutoConnectElement.
Please refer to each [API document](https://hieromon.github.io/AutoConnect/acintro.html) for details.

This topic is closed once because the question is not specific. Reopen when more specific questions arise.

P.S.
The correct value to give to the **onoffswitch-checkbox** class in the LED turning-on handler is "1". It is "2" in your sketch.
