### ISSUE TITLE
Does it work with Arduino + ESP8266 combo through software serial? 

### ISSUE THREAD

**Issue by hk89** [Hieromon/AutoConnect#88]
Title pretty much says it! Does it?

**Comment by Hieromon** [comment]
What for software serial? Do you want to control the ESP8266 using AT commands with NonOS_SDK via software serial from other Arduino boards?
If so, you can't.

**Comment by willfaulds** [comment]
I think this question is about whether you can use this library with an esp8266 based board interfaced with a classic Arduino board e.g. UNO. The idea being run main code on the UNO and the gui/iot aspect on the esp8266. Use software serial to interface the 2 boards. @hk89 that what you’re asking?

**Comment by Hieromon** [comment]
Since there was no response even after one month passed, closed this issue.
When some reports are posted, reopen it.
