### ISSUE TITLE
Is this compatible with the Arduino Uno Wifi Rev2? (it has an ESP32)

### ISSUE THREAD

**Issue by willfaulds** [Hieromon/AutoConnect#92]
Has anyone tried it with the Arduino Uno Wifi Rev2. Any thoughts on whether it should work?

https://www.arduino.cc/en/Guide/ArduinoUnoWiFiRev2

**Comment by scropion86** [comment]
i think as per the [schematics ](https://content.arduino.cc/assets/UNOWiFiREV2V4.0_sch.pdf) the main MCU is ATMEGA4809 not the ESP32 and the pin-outs is not broken out for user to utilize

**Comment by Hieromon** [comment]
@willfaulds, As @scropion86 pointed out, they are different platforms and different frameworks as Arduino implementations.
Before that matter, not even sketch compatibility.
